In [6]:
import pandas as pd

df = pd.read_csv('/Users/anastasia/Downloads/online_retail_II.csv')

In [7]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [8]:
df.shape

(1067371, 8)

In [9]:
df.columns = df.columns.str.lower()

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   invoice      1067371 non-null  str
 1   stockcode    1067371 non-null  str
 2   description  1062989 non-null  str
 3   quantity     1067371 non-null  int64
 4   invoicedate  1067371 non-null  str
 5   price        1067371 non-null  float64
 6   customer id  824364 non-null   float64
 7   country      1067371 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 136.6 MB

In [11]:
df.isnull().sum()

invoice             0
stockcode           0
description      4382
quantity            0
invoicedate         0
price               0
customer id    243007
country             0
dtype: int64

In [12]:
df[df['customer id'].isnull()]

,invoice,stockcode,description,quantity,invoicedate,price,customer id,country
263,489464,21733,85123a mixed,-96,2009-12-01 10:52:00,0.00,NaN,United Kingdom
283,489463,71477,short,-240,2009-12-01 10:52:00,0.00,NaN,United Kingdom
284,489467,85123A,21733 mixed,-192,2009-12-01 10:53:00,0.00,NaN,United Kingdom
470,489521,21646,NaN,-50,2009-12-01 11:44:00,0.00,NaN,United Kingdom
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1066997,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066998,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066999,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
1067000,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
1067001,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

In [13]:
df.describe()

           quantity         price    customer id
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [14]:
df[df['customer id'].isnull()]['price'].sum()

np.float64(1931600.42)

In [15]:
df['invoice'].duplicated().sum()

np.int64(1013743)

In [16]:
df[df['invoice'].duplicated()].head(5)

,invoice,stockcode,description,quantity,invoicedate,price,customer id,country
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom
5,489434,22064,PINK DOUGHNUT TRINKET POT,24,2009-12-01 07:45:00,1.65,13085.0,United Kingdom

In [17]:
df['invoice'].astype(str).str.startswith('C').sum()

np.int64(19494)

In [18]:
df[df['invoice'].str.startswith('C')]

,invoice,stockcode,description,quantity,invoicedate,price,customer id,country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
1065910,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
1067002,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
1067176,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
1067177,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom
1067178,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315.0,United Kingdom

## видно что в датасете есть строки с отменами, занесем их в отдульную таблицу

In [19]:
df_returns = df[df['invoice'].astype(str).str.startswith('C')].copy()

In [20]:
df_returns.shape

(19494, 8)

# у сustomer id много пропусков, необходимо их обработать, но просто удалить все нельзя. 
варианты: 
удалить те где цена 0
пометить служебные типа DOT	DOTCOM POSTAGE	флагом 
удалить те где кол-во отрицательное и удалить все отмены так как они уже в новой таблице

In [21]:
df = df[~df['invoice'].astype(str).str.startswith('C')].copy()

In [22]:
df.shape

(1047877, 8)

In [23]:
df = df[(df['quantity']>0) & (df['price'] > 0)]

In [24]:
df[df['customer id'].isnull()]

,invoice,stockcode,description,quantity,invoicedate,price,customer id,country
577,489525,85226C,BLUE PULL BACK RACING CAR,1,2009-12-01 11:49:00,0.55,NaN,United Kingdom
578,489525,85227,SET/6 3D KIT CARDS FOR KIDS,1,2009-12-01 11:49:00,0.85,NaN,United Kingdom
1055,489548,22271,FELTCRAFT DOLL ROSIE,1,2009-12-01 12:32:00,2.95,NaN,United Kingdom
1056,489548,22254,FELT TOADSTOOL LARGE,12,2009-12-01 12:32:00,1.25,NaN,United Kingdom
1057,489548,22273,FELTCRAFT DOLL MOLLY,3,2009-12-01 12:32:00,2.95,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
1066997,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066998,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
1066999,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
1067000,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
1067001,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

In [25]:
df['is_service'] = df['description'].str.upper().str.contains(
    'POST|BANK|FEE|CHARGE|DOT|CARRIAGE|AMAZON', na=False
)

In [26]:
df_no = df[df['customer id'].notna()].copy()

In [27]:
df_all = df.copy()

In [28]:
df_no.shape

(805549, 9)

In [29]:
df_no.isna().sum()

invoice        0
stockcode      0
description    0
quantity       0
invoicedate    0
price          0
customer id    0
country        0
is_service     0
dtype: int64

# разделила на 2 витрины с пропусками и нет

In [30]:
df_no.describe()

            quantity          price    customer id
count  805549.000000  805549.000000  805549.000000
mean       13.290522       3.206561   15331.954970
std       143.634088      29.199173    1696.737039
min         1.000000       0.001000   12346.000000
25%         2.000000       1.250000   13982.000000
50%         5.000000       1.950000   15271.000000
75%        12.000000       3.750000   16805.000000
max     80995.000000   10953.500000   18287.000000

In [31]:
df_all.describe()

           quantity         price    customer id
count  1.041670e+06  1.041670e+06  805549.000000
mean   1.096346e+01  4.076683e+00   15331.954970
std    1.265150e+02  5.144773e+01    1696.737039
min    1.000000e+00  1.000000e-03   12346.000000
25%    1.000000e+00  1.250000e+00   13982.000000
50%    3.000000e+00  2.100000e+00   15271.000000
75%    1.000000e+01  4.130000e+00   16805.000000
max    8.099500e+04  2.511109e+04   18287.000000

In [32]:
for d in [df_all, df_no, df_returns]:
    d['invoicedate'] = pd.to_datetime(d['invoicedate'])

In [33]:
df_no['customer id'] = df_no['customer id'].astype('int')

In [34]:
df_all['revenue'] = df['quantity']*df['price']

создаем колонку revenue

In [35]:
df_all.head(5)

,invoice,stockcode,description,quantity,invoicedate,price,customer id,country,is_service,revenue
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,False,83.4
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,False,81.0
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,False,100.8
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,False,30.0

In [78]:
import pandas as pd
from sqlalchemy import create_engine


DB_USER = 'postgres'
DB_PASSWORD = '567321'
DB_HOST = 'localhost'
DB_PORT = '5432'
DB_NAME = 'project_retail'


engine = create_engine(
    f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
)


try:
    with engine.connect() as conn:
        print("Подключение к PostgreSQL успешно")
except Exception as e:
    print(f"Ошибка подключения: {e}")

Подключение к PostgreSQL успешно

In [37]:
!pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.14/site-packages (2.9.13)

In [39]:
df_all.to_sql(
    name='sales_all',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=10000,
    method='multi'
)

df_no.to_sql(
    name='sales_customers',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=10000,
    method='multi'
)

df_returns.to_sql(
    name='returns',
    con=engine,
    if_exists='replace',
    index=False,
    chunksize=10000,
    method='multi'
)

print("Готово")

Готово

In [40]:
import pandas as pd

with engine.connect() as conn:
    for table in ['sales_all', 'sales_customers', 'returns']:
        cnt = pd.read_sql(f'SELECT COUNT(*) AS cnt FROM {table}', conn)['cnt'][0]
        print(f"{table}: {cnt:,}")

sales_all: 1,041,670
sales_customers: 805,549
returns: 19,494

In [41]:
rfm = pd.read_csv('/Users/anastasia/Downloads/v_rfm.csv')

In [42]:
rfm.head(5)

   customer_id           last_order  frequency  monetary segments
0        12680  2011-12-09 12:50:00          4     784.0   others
1        13113  2011-12-09 12:49:00         37   18251.0  at risk
2        15804  2011-12-09 12:31:00         13    4206.0  at risk
3        13777  2011-12-09 12:25:00         60   54899.0  at risk
4        17581  2011-12-09 12:21:00         43   17877.0  at risk

In [49]:
rfm[rfm['segments'] == 'at risk'].describe()

        customer_id    frequency       monetary
count   1989.000000  1989.000000    1989.000000
mean   15251.198592    12.989945    6688.690297
std     1703.473700    19.824174   23452.057491
min    12347.000000     1.000000     854.000000
25%    13805.000000     5.000000    1534.000000
50%    15227.000000     8.000000    2786.000000
75%    16709.000000    14.000000    5478.000000
max    18287.000000   395.000000  579454.000000

In [63]:
at_risk = rfm[rfm['segments'] == 'at risk']['monetary']
champions = rfm[rfm['segments'] == 'champion']['monetary']

In [74]:
from scipy import stats

In [75]:
stats.shapiro(at_risk)

ShapiroResult(statistic=np.float64(0.1733687855159485), pvalue=np.float64(6.559168727612862e-69))

In [76]:
stats.shapiro(champions)

ShapiroResult(statistic=np.float64(0.3130457969638155), pvalue=np.float64(1.2179826270143266e-44))

In [77]:
stats, p_value = stats.mannwhitneyu(at_risk, champions, alternative='two-sided')
print(f"p_value = {p_value}")
if p_value < 0.05:
    print('Разница между средней суммой покупки статистически значима')
else:
    print('Разница между средней суммой покупки статистически не значима')

p_value = 2.63919774985741e-32
Разница между средней суммой покупки статистически значима